import './globals.css'
import { Inter } from 'next/font/google'

import Topbar from './components/topbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'poc fe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" bg-gray-900">
        
        <main >
          <div>
            <Topbar />
          </div>
          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
